### ISSUE TITLE
[Feature Request] Use BC furni if exported furnis are from BC

### ISSUE THREAD

**Issue by rafitamolin** [kouris-h/RoomDuplicator#1]
If this extension used Builders Club furni when you export a room that uses furni from the Builders Club catalogue, it would be amazing.

At the moment, if the furni is not present in your inventory, it can't be imported:

![](https://cdn.discordapp.com/attachments/694270878841831475/933824656127967242/unknown.png)

**Comment by WiredSpast** [comment]
It's already on our todo-list since the extension released,  we've just been to busy to work on it
